# Generated by Django 2.1 on 2019-01-28 18:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=32)),
                ('api_path', models.CharField(max_length=1000)),
                ('api_status', models.IntegerField(default=1)),
                ('api_method', models.CharField(max_length=10)),
                ('api_protocol', models.CharField(max_length=10)),
                ('api_response', models.CharField(default='', max_length=1000)),
                ('api_create_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('api_update_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApiHeaders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_name', models.CharField(max_length=32)),
                ('head_value', models.CharField(max_length=1000)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Api')),
            ],
        ),
        migrations.CreateModel(
            name='ApiParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_name', models.CharField(max_length=32)),
                ('param_desc', models.CharField(default='', max_length=1000)),
                ('param_default', models.CharField(default='', max_length=100)),
                ('param_type', models.CharField(max_length=32)),
                ('param_must', models.IntegerField(default=0)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Api')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=32)),
                ('case_desc', models.CharField(default='', max_length=1000)),
                ('case_status', models.IntegerField(default=1)),
                ('case_create_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('case_update_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Env',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env_name', models.CharField(max_length=32)),
                ('env_value', models.CharField(max_length=100)),
                ('env_desc', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('desc', models.CharField(default='', max_length=1000)),
                ('version', models.CharField(default='', max_length=10)),
                ('type', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_type', models.IntegerField(verbose_name='类型1、2、3、4、5、6、7')),
                ('step_sort', models.IntegerField(default=100)),
                ('step_content', models.CharField(max_length=1000)),
                ('step_create_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('step_update_time', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Case')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=32)),
                ('task_desc', models.CharField(default='', max_length=1000)),
                ('task_status', models.IntegerField(default=1)),
                ('task_timer', models.CharField(default='', max_length=1000)),
                ('env_id', models.IntegerField(verbose_name='环境变量ID')),
                ('task_create_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('task_update_time', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
            ],
        ),
        migrations.CreateModel(
            name='TaskCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Case')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Task')),
            ],
        ),
        migrations.AddField(
            model_name='env',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
        ),
        migrations.AddField(
            model_name='case',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
        ),
        migrations.AddField(
            model_name='api',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
        ),
    ]
