# Generated by Django 2.1 on 2019-01-28 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='api',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Api'),
        ),
    ]
