# Generated by Django 2.1 on 2019-02-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_case_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='api_case_coverage',
            field=models.IntegerField(default=0),
        ),
    ]
