# Generated by Django 2.1 on 2019-05-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190304_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseapi',
            name='api_headers',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
