# Generated by Django 2.1 on 2019-06-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_caseapi_api_headers'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseapi',
            name='host',
            field=models.CharField(default='', max_length=255),
        ),
    ]
