# Generated by Django 2.1 on 2019-06-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_caseapi_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='env',
            name='env_value',
            field=models.CharField(max_length=1000),
        ),
    ]
