# Generated by Django 2.1 on 2019-07-25 10:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190619_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(default=0)),
                ('task_no', models.IntegerField(default=0)),
                ('task_result', models.IntegerField(default=1)),
                ('create_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskReportLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.IntegerField(default=0)),
                ('request', models.TextField()),
                ('assertion', models.CharField(default='', max_length=1000)),
                ('response', models.TextField()),
                ('status', models.IntegerField(default=1)),
                ('duration', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('task_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TaskLog')),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='env_id',
        ),
    ]
