# Generated by Django 2.0.2 on 2019-11-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_tasklog_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='step_sort',
            field=models.IntegerField(default=100, verbose_name='1=pre_sqlenv,100=post_reg,101=assertion'),
        ),
    ]
